# Generated by Django 2.0 on 2022-07-14 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PubName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pubname', models.CharField(max_length=255, unique=True, verbose_name='名称')),
            ],
        ),
        migrations.RemoveField(
            model_name='book',
            name='public',
        ),
        migrations.AddField(
            model_name='book',
            name='pub',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='index.PubName'),
        ),
    ]
