# Generated by Django 2.0 on 2022-07-14 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20220714_1729'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtendUserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature', models.CharField(help_text='自建签名', max_length=255, verbose_name='用户签名')),
                ('nickname', models.CharField(help_text='自建昵称', max_length=255, verbose_name='昵称')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='index.UserInfo')),
            ],
        ),
    ]
